name: lint-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    name: Check code formatting and lint code
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          make install

      - name: Check code formatting
        run: |
          make format-check

      - name: Lint code
        run: |
          make lint
